
// Sample product data
export const products = [
    {
      id: 1,
      name: "Off-white Pillow",
      price: 7.99,
      originalPrice: 13.0,
      rating: 5,
      image: "",
      isNew: true,
      discount: 50,
      category: "Accessories",
      description:
        "Super-soft cushion cover in off-white with a tactile pattern that enhances the different tones in the pile and base.",
    },
    {
      id: 2,
      name: "Luxury Sofa",
      price: 299.99,
      originalPrice: 599.99,
      rating: 5,
      image: "/placeholder.svg?height=300&width=300",
      isNew: true,
      discount: 50,
      category: "Living Room",
      description: "Premium comfort with elegant design",
    },
    {
      id: 3,
      name: "Table Lamp",
      price: 59.99,
      rating: 5,
      image: "/placeholder.svg?height=300&width=300",
      isNew: true,
      discount: 50,
      category: "Lighting",
      description: "Modern lighting solution for your space",
    },
    {
      id: 4,
      name: "White Drawer unit",
      price: 89.99,
      rating: 5,
      image: "/placeholder.svg?height=300&width=300",
      isNew: true,
      discount: 50,
      category: "Storage",
      description: "Versatile storage solution",
    },
    {
      id: 5,
      name: "Black Tray table",
      price: 19.99,
      rating: 5,
      image: "/placeholder.svg?height=300&width=300",
      isNew: true,
      discount: 50,
      category: "Living Room",
      description: "Sleek and functional side table",
    },
    {
      id: 6,
      name: "Floor Lamp",
      price: 39.99,
      rating: 5,
      image: "/placeholder.svg?height=300&width=300",
      isNew: true,
      discount: 50,
      category: "Lighting",
      description: "Statement lighting piece",
    },
    {
      id: 7,
      name: "Light Beige Pillow",
      price: 5.99,
      rating: 5,
      image: "/placeholder.svg?height=300&width=300",
      isNew: true,
      discount: 50,
      category: "Accessories",
      description: "Soft and cozy accent pillow",
    },
    {
      id: 8,
      name: "Table Lamp",
      price: 39.99,
      rating: 5,
      image: "/placeholder.svg?height=300&width=300",
      isNew: true,
      discount: 50,
      category: "Lighting",
      description: "Contemporary desk lighting",
    },
    {
      id: 9,
      name: "Bamboo Basket",
      price: 9.99,
      rating: 5,
      image: "/placeholder.svg?height=300&width=300",
      isNew: true,
      discount: 50,
      category: "Storage",
      description: "Eco-friendly storage solution",
    },
  ]
  
  